name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [sid-amd64, bookworm-amd64, bullseye-amd64]
        version: [2.7.8, 3.0.7, 3.1.6, 3.2.7, 3.3.7, 3.4.1]
      fail-fast: false
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: export -p
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - run: rake build:${{ matrix.platform }}:${{ matrix.version }}
      - run: rake test:${{ matrix.platform }}:${{ matrix.version }}
      - run: rm files/binary/.gitkeep files/log/.gitkeep
      - uses: actions/upload-artifact@v4
        with: { name: "binary_${{ matrix.platform }}_${{ matrix.version }}", path: files/binary }
      - uses: actions/upload-artifact@v4
        with: { name: "log_${{ matrix.platform }}_${{ matrix.version }}", path: files/log }

